# Site settings
title: #title
description: #"My first theme for Jekyll"

baseurl: "/"
url: "https:elsalizette-dev.github.io"
markdown: kramdown


include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
  
permalink: /:title

# Default values
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post


# Options
reverse: false
