# Site settings
title: #title
description: #"My first theme for Jekyll"

baseurl: #
markdown: kramdown
permalink: /:title

# Default values
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post


# Options
reverse: false
